version: '3.8'

services:
  mdns_broadcaster:
    build:
      context: ./mdns_broadcaster
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - nginx 

  app_registration:
    build:
      context: ./app_registration
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - mdns_broadcaster
      - nginx 
      
  example_app:
    build:
      context: ./example_app
      dockerfile: Dockerfile
    network_mode: "host"
    # Since host mode is used, ports mapping is not required nor effective.
    depends_on:
      - app_registration
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
    # With host network mode, Nginx will bind directly to the host's port, 
    # so the ports section can be removed as it doesn't apply.