   version: '3.8'

   services:
     mdns_broadcaster:
       image: ${REGISTRY}/tdmx-mdns_broadcaster:latest
       network_mode: "host"
       depends_on:
         - nginx

     app_registration:
       image: ${REGISTRY}/tdmx-app_registration:latest
       network_mode: "host"
       depends_on:
         - mdns_broadcaster
         - nginx

     example_app:
       image: ${REGISTRY}/tdmx-example_app:latest
       network_mode: "host"
       depends_on:
         - app_registration
         - nginx

     nginx:
       image: nginx:alpine
       volumes:
         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
       network_mode: "host"